name: lct-dev

services:
  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
      target: dev
    ports:
      - '4200:4200'
    volumes:
      - .:/app
      - web_node_modules:/app/node_modules
    environment:
      - NODE_ENV=development
    depends_on:
      - api

  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
      target: dev
    ports:
      - '3000:3000'
    volumes:
      - .:/app
      - api_node_modules:/app/node_modules
    environment:
      - NODE_ENV=development

volumes:
  web_node_modules:
  api_node_modules:
