name: nx-stack-prod

services:
  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
      target: prod
    ports:
      - '8080:80'
    environment:
      - NODE_ENV=production
    depends_on:
      - api

  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
      target: prod
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
