name: Deploy to VDS

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Host: ${{ secrets.ssh_host }}"
          echo "User: ${{ secrets.SSH_USER }}"

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy over SSH
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: "188.68.223.222"
          username: "deploy"
          # tmp solution since secrets dont work
          password: "JQkhVFj8OUfefOaz"
          script: |
            cd /home/deploy/app
            git fetch --all
            git reset --hard origin/main
            docker compose -f docker-compose.prod.yml down
            docker compose -f docker-compose.prod.yml build --no-cache
            docker compose -f docker-compose.prod.yml up -d
